srcBasePath: ./src/Generated
apiPackage: API
modelPackage: Model
invokerPackage: Litebase\Generated
artifactVersion: 1.0.0
composerPackageName: litebase/litebase-php
developerOrganization: Litebase
developerOrganizationUrl: https://litebase.com
licenseName: MIT
packageName: Litebase PHP SDK
templateDir: templates
# inputSpec: https://raw.githubusercontent.com/litebase/litebase/refs/heads/main/api/generated_openapi.json
inputSpec: ../../Sites/litebasedb-core/api/generated_openapi.json
generatorName: php
