srcBasePath: ./src
apiPackage: API
modelPackage: Model
invokerPackage: Litebase\OpenAPI
artifactVersion: 1.0.0
composerPackageName: litebase/litebase-php
developerOrganization: Litebase
developerOrganizationUrl: https://litebase.com
licenseName: MIT
packageName: Litebase PHP SDK
outputDir: ./api
templateDir: ./api/templates
inputSpec: https://raw.githubusercontent.com/litebase/litebase/refs/heads/main/api/generated_open_api.json
generatorName: php
variableNamingConvention: camelCase
